#!/usr/bin/env node
// Build-time catalog codegen.
//
// Fetches the live product catalog from the Shopify Storefront API and writes it
// into src/data/catalog.generated.ts in the site's `Product` shape (including the
// real Shopify variant GID, which the cart uses as `merchandiseId` at checkout).
//
// Runs before `next build` (see the "prebuild" npm script). If Shopify isn't
// configured or returns no products, it writes an empty array and the data layer
// falls back to the mock catalog, so the build never breaks.
//
// Env (loaded from .env.local if not already in the environment):
//   NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN
//   NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN
//   NEXT_PUBLIC_SHOPIFY_API_VERSION (optional)

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const OUT = resolve(ROOT, 'src/data/catalog.generated.ts')

// --- Load .env.local if the vars aren't already set --------------------------
function loadEnvLocal() {
  const p = resolve(ROOT, '.env.local')
  if (!existsSync(p)) return
  for (const raw of readFileSync(p, 'utf8').split('\n')) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq === -1) continue
    const key = line.slice(0, eq).trim()
    const val = line.slice(eq + 1).trim()
    if (!(key in process.env)) process.env[key] = val
  }
}
loadEnvLocal()

const DOMAIN = process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN
const TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN
const API_VERSION = process.env.NEXT_PUBLIC_SHOPIFY_API_VERSION || '2025-10'

const banner = '// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.\n// Run `npm run generate:catalog` to refresh from Shopify.\n'

function writeCatalog(products) {
  const body =
    banner +
    "import { Product } from '@/types/product'\n\n" +
    `export const shopifyProducts: Product[] = ${JSON.stringify(products, null, 2)}\n`
  writeFileSync(OUT, body)
}

// --- Map a Shopify product node to the site's Product type -------------------
function categoryFor(title, productType) {
  const s = `${title} ${productType}`.toLowerCase()
  if (/(shirt|tee|crew|hoodie|sweat|tank|long ?sleeve)/.test(s)) return { id: 'mens', name: "Apparel", slug: 'mens', description: 'Premium surf and lifestyle apparel' }
  if (/(bag|tote|sticker|decal|mug|keychain|koozie)/.test(s)) return { id: 'accessories', name: 'Accessories', slug: 'accessories', description: 'Surf and lifestyle accessories' }
  // Default: the current Salted Soul catalog is hats. Shopify products here carry
  // no product type or tags, so anything not clearly apparel/accessory is a hat.
  // When shirts/other lines are added, set the Shopify Product Type so they map right.
  return { id: 'hats', name: 'Hats', slug: 'hats', description: 'Christian hats and caps for faith-forward style' }
}

function mapImage(img, i, altFallback) {
  return {
    id: `img-${i}`,
    url: img?.url ?? '/placeholder.png',
    altText: img?.altText ?? altFallback,
    width: img?.width ?? 1200,
    height: img?.height ?? 1200,
    position: i + 1,
  }
}

function mapProduct(node) {
  const images = (node.images?.edges ?? []).map((e, i) => mapImage(e.node, i, node.title))
  if (images.length === 0 && node.featuredImage) images.push(mapImage(node.featuredImage, 0, node.title))

  const variants = (node.variants?.edges ?? []).map((e) => {
    const v = e.node
    return {
      id: v.id, // real Shopify variant GID — used as merchandiseId at checkout
      name: v.title,
      price: parseFloat(v.price?.amount ?? '0'),
      compareAtPrice: v.compareAtPrice ? parseFloat(v.compareAtPrice.amount) : undefined,
      sku: v.sku ?? '',
      // The public Storefront token can't read exact quantities (that needs the
      // unauthenticated_read_product_inventory scope). Shopify enforces real
      // stock at checkout, so drive the UI off availableForSale: a usable
      // quantity when purchasable, 0 when not.
      inventory: v.availableForSale ? 99 : 0,
      options: (v.selectedOptions ?? []).map((o) => ({ name: o.name, value: o.value })),
      image: v.image ? mapImage(v.image, 0, node.title) : undefined,
      available: Boolean(v.availableForSale),
    }
  })

  const price = parseFloat(node.priceRange?.minVariantPrice?.amount ?? '0')
  const compareAt = node.compareAtPriceRange?.minVariantPrice?.amount
    ? parseFloat(node.compareAtPriceRange.minVariantPrice.amount)
    : undefined
  const category = categoryFor(node.title, node.productType)

  return {
    id: node.id,
    name: node.title,
    slug: node.handle,
    description: node.description || node.title,
    shortDescription: node.description || undefined,
    price,
    compareAtPrice: compareAt && compareAt > price ? compareAt : undefined,
    currency: node.priceRange?.minVariantPrice?.currencyCode ?? 'USD',
    images,
    variants,
    category,
    collections: [],
    tags: node.tags ?? [],
    status: 'active',
    // Surface every live product on the homepage/sections while the catalog is small.
    featured: true,
    bestseller: true,
    newArrival: true,
    onSale: Boolean(compareAt && compareAt > price),
    inventory: { quantity: variants.some((v) => v.available) ? 99 : 0, trackQuantity: false, allowBackorder: false, policy: 'continue' },
    seo: { title: node.title, description: node.description || node.title, keywords: node.tags ?? [] },
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  }
}

const QUERY = `{
  products(first: 100) {
    edges { node {
      id title handle description productType tags availableForSale
      priceRange { minVariantPrice { amount currencyCode } }
      compareAtPriceRange { minVariantPrice { amount } }
      featuredImage { url altText width height }
      images(first: 10) { edges { node { url altText width height } } }
      variants(first: 100) { edges { node {
        id title availableForSale sku
        price { amount currencyCode }
        compareAtPrice { amount }
        selectedOptions { name value }
        image { url altText width height }
      } } }
    } }
  }
}`

async function main() {
  if (!DOMAIN || !TOKEN) {
    console.warn('[catalog] Shopify not configured — writing empty catalog (site falls back to mock data).')
    writeCatalog([])
    return
  }
  console.log(`[catalog] Fetching products from ${DOMAIN} (API ${API_VERSION})…`)
  const res = await fetch(`https://${DOMAIN}/api/${API_VERSION}/graphql.json`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Shopify-Storefront-Access-Token': TOKEN },
    body: JSON.stringify({ query: QUERY }),
  })
  if (!res.ok) throw new Error(`Shopify request failed: ${res.status} ${res.statusText}`)
  const json = await res.json()
  if (json.errors?.length) throw new Error(`Shopify GraphQL error: ${json.errors.map((e) => e.message).join('; ')}`)

  const nodes = (json.data?.products?.edges ?? []).map((e) => e.node)
  const products = nodes.map(mapProduct)
  writeCatalog(products)
  console.log(`[catalog] Wrote ${products.length} product(s) to src/data/catalog.generated.ts`)
  for (const p of products) console.log(`  • ${p.name} — $${p.price} — ${p.variants.length} variant(s) — available: ${p.variants.some((v) => v.available)}`)
}

main().catch((err) => {
  console.error('[catalog] generation failed:', err.message)
  // Don't hard-fail the build — fall back to whatever catalog.generated.ts exists (or mock).
  if (!existsSync(OUT)) writeCatalog([])
  process.exit(0)
})
